### ISSUE TITLE
Gerber

### ISSUE THREAD

**Issue by iskralpust** [paulvee/100MHz-Differential-Probe#1]
Hi I see you have removed the Gerber files for this project. Are you adding new files? It would also be super great is you can add the Diptrace-Eagle files. Thanks.

**Comment by paulvee** [comment]
Yes I did. I wanted to verify the new layouts before I posted the Gerbers. The boards just arrived and I will be adding the components and start testing. very soon. Keep an eye on my blog for this project.

**Comment by iskralpust** [comment]
Awesome looking forward to hearing how it turns out.

**Comment by iskralpust** [comment]
Hi is there any chance you can upload the board and schematic files I was going to make some modifications to the board dimensions for an enclosure and add a 9v battery holder and pcb mount power switch.

**Comment by paulvee** [comment]
iskralpust,
At this moment we do not want to publish more details, in fear that somebody will copy our design and turn it into a commercial product and sell it without us benefiting. This has happened before as you will probably know.
