### ISSUE TITLE
Differential voltage range

### ISSUE THREAD

**Issue by iskralpust** [paulvee/100MHz-Differential-Probe#2]
Hi I saw a comment that you made about how easy it would be to set the gain by changing the 20v/v stage by varying r12. Have you tried or simulated 2v/v to get x100 probe. The diode protection would probably need to be 2 in series for 1.4v clamping this would be well within input voltage range of the first stage assuming the rails are +-2.66v. It would cause some clipping if you exceed 2vpp into the first gain stage but that seems fine as it would not be able to damage anything if its clamped at 1.4v. Thanks.

**Comment by paulvee** [comment]
No, I didn't, but maybe my friend Bud did. He's much better at this than I am, I suggest you ask him.
