### ISSUE TITLE
.CPL Pick and Place file?

### ISSUE THREAD

**Issue by bepstein111** [paulvee/100MHz-Differential-Probe#4]
Would it be possible to provide a .CPL pick and place file? I'm looking to get one or two of these made up with pcbway, and they need a pick and place file. Thanks for your time!

**Comment by paulvee** [comment]
Yes, Diptrace supports Pick & Place, but not in a .CPL file, but a .CSV file.
See if you can use that.

Success!
Paul

[PickandPlace.zip](https://github.com/paulvee/100MHz-Differential-Probe/files/6336672/PickandPlace.zip)



.
