### ISSUE TITLE
wrong opamp in BOM

### ISSUE THREAD

**Issue by shailen001** [paulvee/100MHz-Differential-Probe#5]
Hi,
I just put this probe together. All seems to work except with both terminals connected together, I'm getting x2-x4 noise. 

I think the problem might be the OPAMP in the BOM.

You say LTC6269IMS8E-10, but is it meant to be the lower bandwidth one like in some discussion in blog?

If so, please fix your BOM or others.

Thanks.

**Comment by shailen001** [comment]
Sorry, that can't be my issue. Only applies to x1 probe. x10 should be OK.

**Comment by paulvee** [comment]
The Opamp as listed in the BOM is correct, and the ONLY one to be used.
