### ISSUE TITLE
Pin 1 marker of U4

### ISSUE THREAD

**Issue by wocard2** [paulvee/100MHz-Differential-Probe#9]
The pin 1 marker of U4 is next to pin 5, not pin 1.

**Comment by paulvee** [comment]
No it is not.
https://product.torexsemi.com/system/files/series/xc6216.pdf
And have a look at the picture.

**Comment by wocard2** [comment]
Oops, sorry. I was looking at the board in KiCad, imported from a Eagle file exported by DipTrace. The pin 1 marker was moved by one of the two conversions. I apologize for any inconvenience. Here's what I see in KiCad (flipped view):
![U4](https://github.com/user-attachments/assets/13886c4d-0789-468c-8a63-81fa7f6f1c68)
I don't have Eagle, therefore I cannot check which conversion caused the issue.
